export interface IsoCurrencyDefinition {
    code: string
    name: string
    countryCode: string
    scale: 0 | 2 | 3
}

export const COMMON_CURRENCIES = ['ARS', 'USD', 'EUR', 'BRL', 'CLP', 'UYU', 'GBP', 'MXN'] as const

const SCALE_0 = new Set([
    'BIF', 'CLP', 'DJF', 'GNF', 'ISK', 'JPY', 'KMF', 'KRW', 'PYG', 'RWF', 'UGX', 'VND', 'VUV',
    'XAF', 'XOF', 'XPF',
])
const SCALE_3 = new Set(['BHD', 'IQD', 'JOD', 'KWD', 'LYD', 'OMR', 'TND'])

/**
 * Monedas ISO 4217 activas de curso legal. Se excluyen metales, unidades de cuenta,
 * fondos y códigos de prueba (XAU, XAG, XDR, CLF, COU, BOV, MXV, USN, UYI, CHE,
 * CHW y XTS), porque no pueden utilizarse como dinero cotidiano de un Espacio.
 */
const ACTIVE_LEGAL_TENDER: Array<[string, string, string]> = [
    ['AED', 'Dírham de Emiratos Árabes Unidos', 'AE'],
    ['AFN', 'Afgani afgano', 'AF'],
    ['ALL', 'Lek albanés', 'AL'],
    ['AMD', 'Dram armenio', 'AM'],
    ['ANG', 'Florín caribeño', 'CW'],
    ['AOA', 'Kwanza angoleño', 'AO'],
    ['ARS', 'Peso argentino', 'AR'],
    ['AUD', 'Dólar australiano', 'AU'],
    ['AWG', 'Florín arubeño', 'AW'],
    ['AZN', 'Manat azerbaiyano', 'AZ'],
    ['BAM', 'Marco convertible de Bosnia y Herzegovina', 'BA'],
    ['BBD', 'Dólar de Barbados', 'BB'],
    ['BDT', 'Taka bangladesí', 'BD'],
    ['BGN', 'Lev búlgaro', 'BG'],
    ['BHD', 'Dinar bareiní', 'BH'],
    ['BIF', 'Franco burundés', 'BI'],
    ['BMD', 'Dólar bermudeño', 'BM'],
    ['BND', 'Dólar de Brunéi', 'BN'],
    ['BOB', 'Boliviano', 'BO'],
    ['BRL', 'Real brasileño', 'BR'],
    ['BSD', 'Dólar bahameño', 'BS'],
    ['BTN', 'Ngultrum butanés', 'BT'],
    ['BWP', 'Pula botsuanesa', 'BW'],
    ['BYN', 'Rublo bielorruso', 'BY'],
    ['BZD', 'Dólar beliceño', 'BZ'],
    ['CAD', 'Dólar canadiense', 'CA'],
    ['CDF', 'Franco congoleño', 'CD'],
    ['CHF', 'Franco suizo', 'CH'],
    ['CLP', 'Peso chileno', 'CL'],
    ['CNY', 'Yuan renminbi', 'CN'],
    ['COP', 'Peso colombiano', 'CO'],
    ['CRC', 'Colón costarricense', 'CR'],
    ['CUP', 'Peso cubano', 'CU'],
    ['CVE', 'Escudo caboverdiano', 'CV'],
    ['CZK', 'Corona checa', 'CZ'],
    ['DJF', 'Franco yibutiano', 'DJ'],
    ['DKK', 'Corona danesa', 'DK'],
    ['DOP', 'Peso dominicano', 'DO'],
    ['DZD', 'Dinar argelino', 'DZ'],
    ['EGP', 'Libra egipcia', 'EG'],
    ['ERN', 'Nakfa eritreo', 'ER'],
    ['ETB', 'Birr etíope', 'ET'],
    ['EUR', 'Euro', 'EU'],
    ['FJD', 'Dólar fiyiano', 'FJ'],
    ['FKP', 'Libra malvinense', 'FK'],
    ['GBP', 'Libra esterlina', 'GB'],
    ['GEL', 'Lari georgiano', 'GE'],
    ['GHS', 'Cedi ghanés', 'GH'],
    ['GIP', 'Libra de Gibraltar', 'GI'],
    ['GMD', 'Dalasi gambiano', 'GM'],
    ['GNF', 'Franco guineano', 'GN'],
    ['GTQ', 'Quetzal guatemalteco', 'GT'],
    ['GYD', 'Dólar guyanés', 'GY'],
    ['HKD', 'Dólar de Hong Kong', 'HK'],
    ['HNL', 'Lempira hondureño', 'HN'],
    ['HTG', 'Gourde haitiano', 'HT'],
    ['HUF', 'Forinto húngaro', 'HU'],
    ['IDR', 'Rupia indonesia', 'ID'],
    ['ILS', 'Nuevo séquel israelí', 'IL'],
    ['INR', 'Rupia india', 'IN'],
    ['IQD', 'Dinar iraquí', 'IQ'],
    ['IRR', 'Rial iraní', 'IR'],
    ['ISK', 'Corona islandesa', 'IS'],
    ['JMD', 'Dólar jamaiquino', 'JM'],
    ['JOD', 'Dinar jordano', 'JO'],
    ['JPY', 'Yen japonés', 'JP'],
    ['KES', 'Chelín keniano', 'KE'],
    ['KGS', 'Som kirguís', 'KG'],
    ['KHR', 'Riel camboyano', 'KH'],
    ['KMF', 'Franco comorense', 'KM'],
    ['KPW', 'Won norcoreano', 'KP'],
    ['KRW', 'Won surcoreano', 'KR'],
    ['KWD', 'Dinar kuwaití', 'KW'],
    ['KYD', 'Dólar de las Islas Caimán', 'KY'],
    ['KZT', 'Tenge kazajo', 'KZ'],
    ['LAK', 'Kip laosiano', 'LA'],
    ['LBP', 'Libra libanesa', 'LB'],
    ['LKR', 'Rupia de Sri Lanka', 'LK'],
    ['LRD', 'Dólar liberiano', 'LR'],
    ['LSL', 'Loti lesotense', 'LS'],
    ['LYD', 'Dinar libio', 'LY'],
    ['MAD', 'Dírham marroquí', 'MA'],
    ['MDL', 'Leu moldavo', 'MD'],
    ['MGA', 'Ariary malgache', 'MG'],
    ['MKD', 'Denar macedonio', 'MK'],
    ['MMK', 'Kyat birmano', 'MM'],
    ['MNT', 'Tugrik mongol', 'MN'],
    ['MOP', 'Pataca macaense', 'MO'],
    ['MRU', 'Uguiya mauritano', 'MR'],
    ['MUR', 'Rupia mauriciana', 'MU'],
    ['MVR', 'Rufiyaa maldiva', 'MV'],
    ['MWK', 'Kwacha malauí', 'MW'],
    ['MXN', 'Peso mexicano', 'MX'],
    ['MYR', 'Ringgit malayo', 'MY'],
    ['MZN', 'Metical mozambiqueño', 'MZ'],
    ['NAD', 'Dólar namibio', 'NA'],
    ['NGN', 'Naira nigeriana', 'NG'],
    ['NIO', 'Córdoba nicaragüense', 'NI'],
    ['NOK', 'Corona noruega', 'NO'],
    ['NPR', 'Rupia nepalesa', 'NP'],
    ['NZD', 'Dólar neozelandés', 'NZ'],
    ['OMR', 'Rial omaní', 'OM'],
    ['PAB', 'Balboa panameño', 'PA'],
    ['PEN', 'Sol peruano', 'PE'],
    ['PGK', 'Kina papú', 'PG'],
    ['PHP', 'Peso filipino', 'PH'],
    ['PKR', 'Rupia pakistaní', 'PK'],
    ['PLN', 'Zloty polaco', 'PL'],
    ['PYG', 'Guaraní paraguayo', 'PY'],
    ['QAR', 'Rial catarí', 'QA'],
    ['RON', 'Leu rumano', 'RO'],
    ['RSD', 'Dinar serbio', 'RS'],
    ['RUB', 'Rublo ruso', 'RU'],
    ['RWF', 'Franco ruandés', 'RW'],
    ['SAR', 'Rial saudí', 'SA'],
    ['SBD', 'Dólar de las Islas Salomón', 'SB'],
    ['SCR', 'Rupia seychelense', 'SC'],
    ['SDG', 'Libra sudanesa', 'SD'],
    ['SEK', 'Corona sueca', 'SE'],
    ['SGD', 'Dólar de Singapur', 'SG'],
    ['SHP', 'Libra de Santa Elena', 'SH'],
    ['SLE', 'Leone sierraleonés', 'SL'],
    ['SOS', 'Chelín somalí', 'SO'],
    ['SRD', 'Dólar surinamés', 'SR'],
    ['SSP', 'Libra sursudanesa', 'SS'],
    ['STN', 'Dobra santotomense', 'ST'],
    ['SVC', 'Colón salvadoreño', 'SV'],
    ['SYP', 'Libra siria', 'SY'],
    ['SZL', 'Lilangeni suazi', 'SZ'],
    ['THB', 'Baht tailandés', 'TH'],
    ['TJS', 'Somoni tayiko', 'TJ'],
    ['TMT', 'Manat turcomano', 'TM'],
    ['TND', 'Dinar tunecino', 'TN'],
    ['TOP', 'Paʻanga tongano', 'TO'],
    ['TRY', 'Lira turca', 'TR'],
    ['TTD', 'Dólar de Trinidad y Tobago', 'TT'],
    ['TWD', 'Nuevo dólar taiwanés', 'TW'],
    ['TZS', 'Chelín tanzano', 'TZ'],
    ['UAH', 'Grivna ucraniana', 'UA'],
    ['UGX', 'Chelín ugandés', 'UG'],
    ['USD', 'Dólar estadounidense', 'US'],
    ['UYU', 'Peso uruguayo', 'UY'],
    ['UZS', 'Som uzbeko', 'UZ'],
    ['VED', 'Bolívar digital venezolano', 'VE'],
    ['VES', 'Bolívar soberano venezolano', 'VE'],
    ['VND', 'Dong vietnamita', 'VN'],
    ['VUV', 'Vatu vanuatuense', 'VU'],
    ['WST', 'Tala samoano', 'WS'],
    ['XAF', 'Franco CFA de África Central', 'CM'],
    ['XCD', 'Dólar del Caribe Oriental', 'AG'],
    ['XOF', 'Franco CFA de África Occidental', 'SN'],
    ['XPF', 'Franco CFP', 'PF'],
    ['YER', 'Rial yemení', 'YE'],
    ['ZAR', 'Rand sudafricano', 'ZA'],
    ['ZMW', 'Kwacha zambiano', 'ZM'],
    ['ZWG', 'Zimbabwe Gold', 'ZW'],
]

export const ISO_CURRENCIES: IsoCurrencyDefinition[] = ACTIVE_LEGAL_TENDER.map(
    ([code, name, countryCode]) => ({
        code,
        name,
        countryCode,
        scale: SCALE_0.has(code) ? 0 : SCALE_3.has(code) ? 3 : 2,
    })
)

const CURRENCIES_BY_CODE = new Map(ISO_CURRENCIES.map((currency) => [currency.code, currency]))

export function getIsoCurrency(code: string) {
    return CURRENCIES_BY_CODE.get(code.trim().toUpperCase())
}

export function isActiveLegalTenderCurrency(code: string) {
    return CURRENCIES_BY_CODE.has(code.trim().toUpperCase())
}

export function getCurrencyScale(code: string) {
    return getIsoCurrency(code)?.scale
}
